development:
  adapter: postgresql
  database: nevereatalone_development

staging:
  adapter: postgresql
  database: nevereatalone_staging

production:
  adapter: postgresql
  database: nevereatalone_production
